"""add_space_members

Revision ID: 18b2fa29171e
Revises: 2b52b27118ec
Create Date: 2026-04-22 22:44:20.829242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18b2fa29171e'
down_revision: Union[str, Sequence[str], None] = '2b52b27118ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otp_codes')
    op.alter_column('burn_rate_alerts', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('client_budgets', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('client_budgets_org_id_client_month_year_key'), 'client_budgets', type_='unique')
    op.create_unique_constraint('uq_budget_org_client_month', 'client_budgets', ['org_id', 'client', 'month', 'year'])
    op.alter_column('epics', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('epics', 'pod',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('epics', 'color',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('knowledge_gaps', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('knowledge_gaps', 'wiki_coverage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('knowledge_gaps', 'example_tickets',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('manual_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('manual_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('notifications', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('organisations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('organisations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sprints', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('sprints', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'planning'::text"))
    op.alter_column('sprints', 'pod',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('standups', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('standups_user_id_date_key'), 'standups', type_='unique')
    op.alter_column('ticket_comments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_te_ivfflat'), table_name='ticket_embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('ticket_embeddings', 'embedding')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('users_invited_by_fkey'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_we_ivfflat'), table_name='wiki_embeddings', postgresql_with={'lists': '50'}, postgresql_using='ivfflat')
    op.drop_column('wiki_embeddings', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki_embeddings', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_we_ivfflat'), 'wiki_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '50'}, postgresql_using='ivfflat')
    op.create_foreign_key(op.f('users_invited_by_fkey'), 'users', 'users', ['invited_by'], ['id'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('ticket_embeddings', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_te_ivfflat'), 'ticket_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('ticket_comments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_unique_constraint(op.f('standups_user_id_date_key'), 'standups', ['user_id', 'date'])
    op.alter_column('standups', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('sprints', 'pod',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sprints', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'planning'::text"))
    op.alter_column('sprints', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('organisations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('organisations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('notifications', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('manual_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('manual_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('knowledge_gaps', 'example_tickets',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('knowledge_gaps', 'wiki_coverage',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('knowledge_gaps', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('epics', 'color',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('epics', 'pod',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('epics', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('uq_budget_org_client_month', 'client_budgets', type_='unique')
    op.create_unique_constraint(op.f('client_budgets_org_id_client_month_year_key'), 'client_budgets', ['org_id', 'client', 'month', 'year'])
    op.alter_column('client_budgets', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('burn_rate_alerts', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('otp_codes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('otp_codes_pkey'))
    )
    # ### end Alembic commands ###
